### ISSUE TITLE
Clearing text with the clear button in UITextField doesn't propagate

### ISSUE THREAD

**Issue by cajurabi** [DeclarativeHub/Bond#539] opened 2018-07-17 00:55 UTC
Pretty gnarly bug for the end user, when they expect the text to be cleared, and it isn't--I can imagine text messages being sent/saved that should have never seen the light of day.  This is happening with a bidrectionalBind on UITextFields.  This bug makes it not possible (responsible) to use on textFields with the clear button enabled.  I suspect this is similar to the autocorrect bug reported in April (#519 )

**Comment by srdanrasic** [comment] 2018-11-11 15:11
Yeah, this is a duplicate of #519. Unfortunately I don't have any update on this at the moment.

**Closed by srdanrasic** 2018-11-11 15:11 UTC
